# Curso Python Aula 02 - Para que serve o Python?

# Aborda as origens do Python, uma linguagem de programação criada por Guido van Rossum em 1989, com o objetivo de proporcionar uma linguagem simples e amigável ao usuário. Python ganhou popularidade devido à facilidade de aprendizado e ao seu uso em diversas indústrias, como desenvolvimento de produtos, jogos e biotecnologia. O vídeo destaca a importância de aprender a linguagem de forma incremental e mostra várias organizações, como o Google, a NASA, e jogos populares desenvolvidos usando Python. O vídeo também menciona o curso de Python criado pelo seu criador, voltado para iniciantes, e enfatiza a necessidade de apoio da comunidade para torná-lo uma realidade.

# Nesta seção, é explicado que a linguagem de programação Python foi lançada inicialmente no início dos anos 90 e ganhou popularidade entre a comunidade devido à sua simplicidade e facilidade de aprendizado. Guido Van Rossum, o criador do Python, iniciou o projeto para ensinar programação às pessoas, o que resultou no desenvolvimento do projeto CT4, financiado pela agência DARPA do governo dos Estados Unidos. Atualmente, o Python é suportado por empresas como Microsoft, Google e até mesmo pela empresa de transmissão brasileira Globo. Com sua evolução, o Python se tornou uma das linguagens padrão pré-instaladas em muitos sistemas operacionais, exceto o Windows. A linguagem tem sido amplamente utilizada em diversas aplicações, incluindo projetos de IoT e até mesmo uma biblioteca que instala o Minecraft em um Raspberry Pi para ensinar programação a jovens. Finalmente, é observado que Guido Van Rossum ainda está ativamente envolvido no desenvolvimento do Python e atualmente trabalha no Dropbox.

# Nesta seção, é explicado como o Python é usado em diversas indústrias, como desenvolvimento de produtos, jogos e produção de filmes devido à sua simplicidade, facilidade e funcionalidade multiplataforma. Python é ótimo para iniciantes, pois vem com "baterias inclusas", é de código aberto e possui uma filosofia clara que enfatiza simplicidade, legibilidade e organização. Python é uma linguagem orientada a objetos e está repleta de bibliotecas para desenvolvimento de aplicativos, jogos e sistemas. Sua filosofia inclui a criação de código bonito, simples e legível e não deixar erros passarem despercebidos.

# Nesta seção, o vídeo discute as diversas aplicações do Python em várias indústrias e empresas, enfatizando sua capacidade de lidar com cálculos em larga escala necessários em campos como biotecnologia e computação 3D. O vídeo dá vários exemplos de grandes corporações, como o Google e a NASA, que utilizam o Python, juntamente com jogos populares como Civilization IV e Battlefield 2, que são desenvolvidos usando a linguagem. O vídeo enfatiza a necessidade de focar no processo de aprendizado ao começar com o Python, em vez de tentar avançar para projetos avançados imediatamente.

# Nesta seção, o criador do vídeo discute seu curso de Python e a necessidade de apoio financeiro dos espectadores para torná-lo uma realidade completa. O curso é projetado para iniciantes, sem pré-requisitos, e tem como objetivo ensinar a linguagem de forma abrangente por meio de uma variedade de exercícios e materiais. O criador admite que tem sido uma jornada desafiadora de quatro anos para produzir conteúdo de qualidade e está solicitando o apoio da comunidade e dos estudantes para garantir que o curso seja concluído. Na próxima lição, os espectadores aprenderão como instalar o Python em suas máquinas e começar com os conceitos básicos de programação.
